name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas plotly

      - name: Run script
        run: python nume_fisierul_tau.py  # <-- Pune aici numele fisierului tau .py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Update map with delete button" || exit 0
          git push
