name: Generare Harta Neon 2026

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Îți permite să rulezi scriptul manual de pe GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install folium

      - name: Run script
        run: python harta.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: harta-interactiva
          path: harta_prologistics_2026.html
